services:
  - type: web
    name: multiblog
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn multiblog_project.wsgi --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: multiblog-qdr2.onrender.com
      - key: PYTHON_VERSION
        value: 3.12.8
